// Generated by Resultant (Test Materialization)
// Source Test Definition: TD-T-ENDPOINT-PUT-ARTICLES
// Do not edit by hand; regenerate via Resultant.

package resultant_test

import (
	"net/http"
	"os"
	"strings"
	"testing"
)

// Endpoint behavior: PUT /articles/
// Test Definition: TD-T-ENDPOINT-PUT-ARTICLES
func TestTd_t_endpoint_put_articles(t *testing.T) {
	base := os.Getenv("RESULTANT_BASE_URL")
	if base == "" {
		t.Fatalf("RESULTANT_BASE_URL is not set: the service under test has no address. " +
			"Refusing rather than skipping, because a skipped test exits 0 and reads as a pass.")
	}

	{
		body := strings.NewReader("{}")
		req, err := http.NewRequest("PUT", base+"/articles/", body)
		if err != nil {
			t.Fatalf("/articles/: could not build request: %v", err)
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			t.Fatalf("/articles/: request failed: %v", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != 200 {
			t.Errorf("expected 200 for /articles/, got %d", resp.StatusCode)
		}
	}
}
